In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')

In [2]:
dataset = pd.read_csv('binary_log.csv')

In [3]:
dataset

      SAT Admitted  Gender
0    1363       No    Male
1    1792      Yes  Female
2    1954      Yes  Female
3    1653       No    Male
4    1593       No    Male
..    ...      ...     ...
163  1722      Yes  Female
164  1750      Yes    Male
165  1555       No    Male
166  1524       No    Male
167  1461       No    Male

[168 rows x 3 columns]

In [4]:
dataset['Admitted']=dataset['Admitted'].map({'No':0,'Yes':1})
dataset['Gender']=dataset['Gender'].map({'Male':0,'Female':1})

In [5]:
dataset

      SAT  Admitted  Gender
0    1363         0       0
1    1792         1       1
2    1954         1       1
3    1653         0       0
4    1593         0       0
..    ...       ...     ...
163  1722         1       1
164  1750         1       0
165  1555         0       0
166  1524         0       0
167  1461         0       0

[168 rows x 3 columns]

In [6]:
X = dataset.iloc[:,[0,2]].values

In [7]:
X

array([[1363,    0],
       [1792,    1],
       [1954,    1],
       [1653,    0],
       [1593,    0],
       [1755,    1],
       [1775,    1],
       [1887,    1],
       [1893,    1],
       [1580,    0],
       [1857,    1],
       [1880,    1],
       [1664,    1],
       [1364,    0],
       [1693,    0],
       [1850,    1],
       [1633,    0],
       [1634,    0],
       [1636,    1],
       [1855,    1],
       [1987,    1],
       [1997,    0],
       [1422,    1],
       [1508,    1],
       [1720,    1],
       [1879,    0],
       [1634,    1],
       [1802,    0],
       [1849,    1],
       [1764,    1],
       [1460,    0],
       [1675,    1],
       [1656,    0],
       [2020,    0],
       [1850,    0],
       [1865,    0],
       [1664,    0],
       [1872,    1],
       [1654,    0],
       [1393,    1],
       [1587,    0],
       [1631,    1],
       [1931,    0],
       [1370,    0],
       [1810,    0],
       [1414,    0],
       [1761,    1],
       [1477,    0],
       [1486,    0],
       [1561,    0],
       [1549,    0],
       [2050,    0],
       [1697,    1],
       [1543,    1],
       [1934,    1],
       [1385,    0],
       [1670,    0],
       [1735,    1],
       [1634,    0],
       [1777,    1],
       [1550,    0],
       [1715,    0],
       [1925,    1],
       [1842,    0],
       [1786,    0],
       [1435,    0],
       [1387,    0],
       [1521,    0],
       [1975,    1],
       [1435,    0],
       [1714,    0],
       [1634,    0],
       [1464,    1],
       [1794,    0],
       [1855,    0],
       [1953,    0],
       [1469,    0],
       [1663,    0],
       [1907,    1],
       [1990,    1],
       [1542,    0],
       [1808,    1],
       [1966,    1],
       [1679,    1],
       [2021,    1],
       [2015,    1],
       [1473,    0],
       [1979,    0],
       [1787,    1],
       [1687,    1],
       [1674,    1],
       [1478,    1],
       [1735,    1],
       [1720,    1],
       [1494,    0],
       [1964,    0],
       [1843,    1],
       [1550,    1],
       [1764,    1],
       [1712,    1],
       [1775,    1],
       [1531,    0],
       [1781,    1],
       [1579,    0],
       [1526,    1],
       [1778,    1],
       [1769,    1],
       [1824,    1],
       [1481,    0],
       [1464,    0],
       [1591,    0],
       [1666,    0],
       [1455,    0],
       [1934,    1],
       [1625,    0],
       [1334,    0],
       [1721,    1],
       [1475,    0],
       [1662,    1],
       [1861,    1],
       [1936,    1],
       [1572,    0],
       [1508,    1],
       [1430,    0],
       [1891,    1],
       [1550,    0],
       [1741,    1],
       [1690,    0],
       [1687,    0],
       [1730,    0],
       [1674,    1],
       [1475,    0],
       [1962,    1],
       [1532,    0],
       [1492,    0],
       [1502,    0],
       [1974,    1],
       [1607,    0],
       [1412,    1],
       [1557,    0],
       [1821,    0],
       [1760,    1],
       [1685,    0],
       [1773,    1],
       [1826,    1],
       [1565,    1],
       [1510,    0],
       [1374,    0],
       [1402,    0],
       [1702,    0],
       [1956,    1],
       [1933,    0],
       [1832,    0],
       [1893,    0],
       [1831,    1],
       [1487,    0],
       [2041,    1],
       [1850,    0],
       [1555,    1],
       [2020,    1],
       [1593,    0],
       [1934,    1],
       [1808,    0],
       [1722,    1],
       [1750,    0],
       [1555,    0],
       [1524,    0],
       [1461,    0]], dtype=int64)

In [8]:
y = dataset.iloc[:,1].values

In [9]:
y

array([0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0], dtype=int64)

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [12]:
X_train.shape

(134, 2)

In [13]:
X_test.shape

(34, 2)

In [14]:
from keras.models import Sequential
from keras.layers import Dense

In [15]:
model = Sequential()
model.add(Dense(8,activation='relu',input_dim=2))
model.add(Dense(8,activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 8)                 24
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 72
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 72
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 9
=================================================================
Total params: 177
Trainable params: 177
Non-trainable params: 0
_________________________________________________________________

In [17]:
model.compile(loss='binary_crossentropy',optimizer='adam')

In [18]:
model.fit(X_train,y_train,epochs=100)

Epoch 1/100
5/5 [==============================] - 1s 4ms/step - loss: 259.0140
Epoch 2/100
5/5 [==============================] - 0s 4ms/step - loss: 237.0990
Epoch 3/100
5/5 [==============================] - 0s 4ms/step - loss: 216.6096
Epoch 4/100
5/5 [==============================] - 0s 6ms/step - loss: 195.6109
Epoch 5/100
5/5 [==============================] - 0s 4ms/step - loss: 177.1864
Epoch 6/100
5/5 [==============================] - 0s 4ms/step - loss: 159.5433
Epoch 7/100
5/5 [==============================] - 0s 6ms/step - loss: 141.8117
Epoch 8/100
5/5 [==============================] - 0s 4ms/step - loss: 125.4709
Epoch 9/100
5/5 [==============================] - 0s 4ms/step - loss: 109.1850
Epoch 10/100
5/5 [==============================] - 0s 6ms/step - loss: 93.3186
Epoch 11/100
5/5 [==============================] - 0s 6ms/step - loss: 79.4082
Epoch 12/100
5/5 [==============================] - 0s 4ms/step - loss: 64.0507
Epoch 13/100
5/5 [==============================] - 0s 4ms/step - loss: 50.4194
Epoch 14/100
5/5 [==============================] - 0s 4ms/step - loss: 42.2365
Epoch 15/100
5/5 [==============================] - 0s 4ms/step - loss: 37.7726
Epoch 16/100
5/5 [==============================] - 0s 2ms/step - loss: 33.9487
Epoch 17/100
5/5 [==============================] - 0s 4ms/step - loss: 30.0321
Epoch 18/100
5/5 [==============================] - 0s 4ms/step - loss: 25.6994
Epoch 19/100
5/5 [==============================] - 0s 4ms/step - loss: 21.0222
Epoch 20/100
5/5 [==============================] - 0s 4ms/step - loss: 16.4657
Epoch 21/100
5/5 [==============================] - 0s 6ms/step - loss: 11.5477
Epoch 22/100
5/5 [==============================] - 0s 4ms/step - loss: 6.3568
Epoch 23/100
5/5 [==============================] - 0s 6ms/step - loss: 1.6508
Epoch 24/100
5/5 [==============================] - 0s 6ms/step - loss: 3.6894
Epoch 25/100
5/5 [==============================] - 0s 6ms/step - loss: 2.5776
Epoch 26/100
5/5 [==============================] - 0s 4ms/step - loss: 1.2019
Epoch 27/100
5/5 [==============================] - 0s 4ms/step - loss: 1.8330
Epoch 28/100
5/5 [==============================] - 0s 4ms/step - loss: 0.8634
Epoch 29/100
5/5 [==============================] - 0s 6ms/step - loss: 0.9914
Epoch 30/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6940
Epoch 31/100
5/5 [==============================] - 0s 4ms/step - loss: 0.7057
Epoch 32/100
5/5 [==============================] - 0s 4ms/step - loss: 0.7157
Epoch 33/100
5/5 [==============================] - 0s 5ms/step - loss: 0.6857
Epoch 34/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6997
Epoch 35/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6693
Epoch 36/100
5/5 [==============================] - 0s 6ms/step - loss: 0.6640
Epoch 37/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6705
Epoch 38/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6704
Epoch 39/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6725
Epoch 40/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6590
Epoch 41/100
5/5 [==============================] - 0s 6ms/step - loss: 0.6631
Epoch 42/100
5/5 [==============================] - 0s 6ms/step - loss: 0.6643
Epoch 43/100
5/5 [==============================] - 0s 6ms/step - loss: 0.6578
Epoch 44/100
5/5 [==============================] - 0s 6ms/step - loss: 0.6730
Epoch 45/100
5/5 [==============================] - 0s 6ms/step - loss: 0.6845
Epoch 46/100
5/5 [==============================] - 0s 6ms/step - loss: 0.7010
Epoch 47/100
5/5 [==============================] - 0s 6ms/step - loss: 0.6837
Epoch 48/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6770
Epoch 49/100
5/5 [==============================] - 0s 6ms/step - loss: 0.6647
Epoch 50/100
5/5 [==============================] - ETA: 0s - loss: 0.666 - 0s 8ms/step - loss: 0.6606
Epoch 51/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6604
Epoch 52/100
5/5 [==============================] - 0s 6ms/step - loss: 0.6843
Epoch 53/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6591
Epoch 54/100
5/5 [==============================] - 0s 12ms/step - loss: 0.7011
Epoch 55/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6643
Epoch 56/100
5/5 [==============================] - 0s 5ms/step - loss: 0.6773
Epoch 57/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6944
Epoch 58/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6661
Epoch 59/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6604
Epoch 60/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6686
Epoch 61/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6607
Epoch 62/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6583
Epoch 63/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6559
Epoch 64/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6597
Epoch 65/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6562
Epoch 66/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6561
Epoch 67/100
5/5 [==============================] - 0s 2ms/step - loss: 0.6600
Epoch 68/100
5/5 [==============================] - 0s 2ms/step - loss: 0.6564
Epoch 69/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6565
Epoch 70/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6626
Epoch 71/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6805
Epoch 72/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6665
Epoch 73/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6589
Epoch 74/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6606
Epoch 75/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6637
Epoch 76/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6558
Epoch 77/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6811
Epoch 78/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6783
Epoch 79/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6726
Epoch 80/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6578
Epoch 81/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6570
Epoch 82/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6598
Epoch 83/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6478
Epoch 84/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6909
Epoch 85/100
5/5 [==============================] - 0s 4ms/step - loss: 0.7102
Epoch 86/100
5/5 [==============================] - 0s 4ms/step - loss: 0.7134
Epoch 87/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6642
Epoch 88/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6741
Epoch 89/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6561
Epoch 90/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6784
Epoch 91/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6619
Epoch 92/100
5/5 [==============================] - 0s 2ms/step - loss: 0.6664
Epoch 93/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6743
Epoch 94/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6614
Epoch 95/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6587
Epoch 96/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6536
Epoch 97/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6575
Epoch 98/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6527
Epoch 99/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6870
Epoch 100/100
5/5 [==============================] - 0s 4ms/step - loss: 0.6547

In [19]:
y_pred = model.predict(X_test)

In [20]:
y_pred.round()

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)

In [21]:
y_test

array([1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1], dtype=int64)